# Generated by Django 4.1.7 on 2024-01-16 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('fuel', models.CharField(max_length=50)),
                ('power', models.PositiveIntegerField()),
                ('horse_power', models.PositiveIntegerField()),
                ('plate', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Service'), (2, 'Repairs')])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('car_id', models.ForeignKey(blank=True, db_column='car_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='carservice_api.car')),
            ],
            options={
                'db_table': 'maintenance',
            },
        ),
    ]
