# Generated by Django 4.1.7 on 2024-01-23 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carservice_api', '0001_InitializeDB'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sercice_type', models.IntegerField(choices=[(1, 'Change'), (2, 'Check')])),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('mileage', models.IntegerField()),
                ('maintenance_id', models.ForeignKey(blank=True, db_column='maintenance_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='carservice_api.maintenance')),
            ],
            options={
                'db_table': 'service',
            },
        ),
    ]
