# Generated by Django 4.1.7 on 2024-01-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carservice_api', '0002_CreateServiceTableDB'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='sercice_type',
            new_name='service_type',
        ),
    ]
