# Generated by Django 4.1.7 on 2024-01-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice_api', '0003_ChangeFieldNameInServiceTableDB'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='mileage',
            field=models.IntegerField(blank=True),
        ),
    ]
